global:
  resolve_timeout: 1m
  slack_api_url: ''
route:
  receiver: 'slack'
receivers:
- name: 'slack'
  slack_configs:
    - channel: '#prometheus-alerts'
      send_resolved: true
      icon_url: https://avatars3.githubusercontent.com/u/3380462
      text: >-
       {{ range .Alerts -}}
       *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

       *Description:* {{ .Annotations.description }}

       *Details:*
         {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
         {{ end }}
       {{ end }}
